### ISSUE TITLE
Error after weighted HPFi added to unsampled image

### ISSUE THREAD

**Issue by SFrav** [NikosAlexandris/i.fusion.hpf#5]
I get the following error output when trying to pan sharpen a Landsat 8 image. I have tried various combinations of flags and settings, but not working yet. This is on Grass 7 beta 4.

`<i.fusion.hpf -l -c --o pan=LC81670652014059LGN00_B8 msx=LC81670652014059LGN00_B2,LC81670652014059LGN00_B3,LC81670652014059LGN00_B 4 center=high modulation=max >`

|5 Adding weighted HPFi to upsampled image

|* Matching output to input color table
WARNING: Unable to rename null file 'D:\user\Documents\grassdata/newLocation/Morogoro/.tmp/unknown/5664.1' to 'D:\userl\Documents\grassdata/newLocation/Morogoro/cell_misc/tmp.6716.0_msx_hpf/null': File exists
WARNING: Unable to rename cell file 'D:\user\Documents\grassdata/newLocation/Morogoro/.tmp/unknown/5664.0' to 'D:\user\Documents\grassdata/newLocation/Morogoro/fcell/tmp.6716.0_msx_hpf': File exists
ERROR: g.rename: Sorry, <rast=> is ambiguous
Traceback (most recent call last):
  File ".\i.fusion.hpf.py", line 588, in <module>
    sys.exit(main())
  File ".\i.fusion.hpf.py", line 576, in main
    run("g.rename", rast=(tmp_msx_hpf, msx_nam))
  File ".\i.fusion.hpf.py", line 210, in run
    grass.run_command(cmd, quiet=True, **kwargs)
  File "C:\Program Files (x86)\GRASS GIS
7.0.0beta4\etc\python\grass\script\core.py", line 373, in
run_command
    return handle_errors(returncode, returncode, args,
kwargs)
  File "C:\Program Files (x86)\GRASS GIS
7.0.0beta4\etc\python\grass\script\core.py", line 308, in
handle_errors
    returncode=returncode)
grass.exceptions.CalledModuleError: Module run None
['g.rename', '--q',
'rast=tmp.6716.0_msx_hpf,LC81670652014059LGN00_B2.hpf']
ended with error
Process ended with non-zero return code 1. See errors in the
(error) output.

**Comment by NikosAlexandris** [comment]
These errors, to the best of my knowledge, are related to recent changes in GRASS itself:  the "rast" parameter, for all grass modules, is renamed to "raster".  I updated `i.fusion.hpf`. I guess it should work now. Let me, please, know.

ps- do you really work with Windows?  How did you compile the module? I can update the instructions for Windows users.

Thank you.
