### ISSUE TITLE
NameError in a specific branch

### ISSUE THREAD

**Issue by pmav99** [NikosAlexandris/i.fusion.hpf#9]
Minor nitpick, there is an undefined variable/function [here](https://github.com/NikosAlexandris/i.fusion.hpf/blob/931189ff9517f638ec636bd36546144a47caa127/i.fusion.hpf.py#L367). I.e the underscore (`_`) is not defined.

**Comment by NikosAlexandris** [comment]
See http://permalink.gmane.org/gmane.comp.gis.grass.devel/65223

**Comment by pmav99** [comment]
Shouldn't you use something like this then?
``` python
from gettext import gettext as _
```
If you don't, unless GRASS is doing something magical behind the scenes, you are going to get a NameError.

**Comment by NikosAlexandris** [comment]
I think GRASS is doing something magical. You may want to check that this exists in many scripts, in the grass-addons dir: `grep -r 'fatal' */*`.
